services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    networks:
      - my-network
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-docker}
      POSTGRES_DB: ${POSTGRES_DB:-example}
    ports:
      - "${PG_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-docker}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-mongo}
      MONGO_INITDB_DATABASE: ${MONGO_DATA:-example}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/etc/mongo
  server:
    container_name: my-server
    restart: unless-stopped
    depends_on:
      - postgres
      - mongo
    build:
      context: ./server/
    ports:
      - "1234:1234"
    networks:
      - my-network
  client:
    container_name: my-client
    restart: unless-stopped
    depends_on:
      - server
    build:
      context: ./client/
    ports:
      - "4173:4173"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
volumes:
  postgres_data:
  mongo_data:
