services:
  server:
    container_name: my-server
    build:
      context: ./server/
    ports:
      - "1234:1234"
    networks:
      - my-network
  client:
    container_name: my-client
    build:
      context: ./client/
    ports:
      - "4173:4173"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
