services:
  server:
    container_name: my-server
    restart: unless-stopped
    depends_on:
      - postgres
      - mongo
    build:
      context: .
    ports:
      - "${SERVER_PORT:-1234}:${SERVER_PORT:-1234}"
    networks:
      - my-network
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    networks:
      - my-network
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-user}
      POSTGRES_USER: ${POSTGRES_USER:-password}
      POSTGRES_DB: ${POSTGRES_DB:-example}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    networks:
      - my-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-docker}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-mongo}
      MONGO_INITDB_DATABASE: ${MONGO_DATA:-example}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/etc/mongo

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
